using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GMTool.Enums
{
    public enum SubCategory
    {
        NONE,
        ALCHEMIST_BOX,
        ALCHEMIST_KIT,
        APPEARANCE,
        ARTIFACT,
        AVATAR_BOOTS,
        AVATAR_GLOVES,
        AVATAR_HELM,
        AVATAR_PACK,
        AVATAR_PACKAGE,
        AVATAR_PANTS,
        AVATAR_SET,
        AVATAR_TUNIC,
        BADGE,
        BEARD,
        BELT,
        BODYPAINTING,
        BOOTS,
        BRACELET,
        BULLET,
        CAPSULE,
        CASHITEM,
        CASTLET,
        CHARM,
        CLEANER,
        COMBINE_PART,
        EARRING,
        EPAULET,
        ERG,
        ETC,
        EYEBROW,
        FACEPAINTING,
        FEATHER,
        GACHA_AVATAR,
        GACHA_WEAPON,
        GARBAGE,
        GEMSTONE,
        GLOVES,
        HAIR,
        HELM,
        INNERARMOR,
        KIT,
        LARGESHIELD,
        MAKEUP,
        MANA_GEM,
        NECKLACE,
        PACKAGE,
        PANTS,
        PATTERN,
        POTION,
        QUESTSCROLL,
        RAREITEM,
        REAR,
        RING,
        SCAR,
        SCROLL,
        SHIELD,
        SKILLBOOK,
        SKILL_ENHANCE_STONE,
        SPELLBOOK,
        STORYSCROLL,
        SUBWEAPON,
        TAIL,
        TITLESCROLL,
        TOWN_EFFECT,
        TUNIC,
        WEAPON,
    }
}
